services:
  api:
    container_name: esestock
    build:
      context: .
    ports:
      - "8082:8082"
    networks:
      - eseklugdorow

networks:
  eseklugdorow:
    name: eseklugdorow
    external: true