server:
  servlet:
    context-path: /
  port:
    8082
    
spring:
  config:
    import: env.properties
  application:
    name: esestock
  datasource:
    url: jdbc:postgresql://ese-stock-ese-stock.h.aivencloud.com:24576/stock?ssl=require
    username: avnadmin
    password: ${POSTGRESQL_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

openapi:
  service:
    title: esestock doc
    version: 1.0.0
    url: http://eseapigateway:8080

springdoc:
  api-docs:
    path: /esestock/v3/api-docs
  swagger-ui:
    path: /esestock/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true